### ISSUE TITLE
2019.4 第二期

### ISSUE THREAD

**Issue by SHERlocked93** [Read-Book2019/Schedule#6]
#4 #5 

| 成员     | 正在阅读 | W1 | W2 | W3 | W4 |
|----------|----------|----|----|----|----|
| 高高     |    你不知道的JS 上      |     |     ✔︎|    |    |
| 鑫       |     你不知道的JS 上     |  ✔︎  |    |  ✔︎  |  ✔︎  |
| 阳       |     你不知道的JS 上     |  ✔︎  |    |  ✔︎  |    |
| 电扇君   |          |     |    |    |    |
| Gkr      |     你不知道的JS 上     |    |    |  ✔︎  |  ✔︎  |
| 墨言     |          |     |    |    |    |
| 阿飞     |          |    |    |    |    |
| 明       |     你不知道的JS 上     |     |  ✔︎  |    |    |
| 一男     |          |   |    |    |    |
| mono     |          |    |    |    |    |
| 雪舞     |          |     |    |    |    |
| 俊俊酱   |      |     |    |    |    |
| 键       |     图解HTTP     |   ✔︎  |  ✔︎  |  ✔︎  |  ✔︎  |
| 阿车     |     你不知道的JS 上     |   ✔︎  |    |  ✔︎  |  ✔︎  |
| fish     |     你不知道的JS 上     |  ✔︎  |  ✔︎  |  ✔︎  |  ✔︎  |
| sweet    |       你不知道的JS 上    |     |  ✔︎  |  ✔︎  |  ✔︎  |
| Hz    |     你不知道的JS 上     |   ✔︎  |    |  ✔︎  |  ✔︎  |
| 笑妄     |          |    |    |    |    |
| SHER93   |    HTTP/2基础教程      |   ✔︎  |  ✔︎  |  ✔︎  |  ✔︎  |

**Comment by SHERlocked93** [comment]
#打卡#  SHERlocked93  《HTTP/2基础教程》
有一些不错的点可以跟大家分享一下
1. 2010 年，谷歌把 Web 性能作为影响页面搜索评分的重要因素之一，性能指标开始在搜索引擎中发挥作用
2. HTTP/1.1 里面一些优化的模式，在HTTP/2里面成了反模式，这在升级的时候需要注意
3. 任何不支持 h2 的客户端都将简单地退回到 h1，仍然可以访问你的站点基础设施，类似于平稳退化

**Comment by Java-http** [comment]
#打卡# 鑫 《你不知道的js上册》
分享：
1. this 绑定意外其中有个间接引用，babel转译import {xx} 后代码也用到，附上我一[笔记内容](https://java-http.github.io/1553734007761/)
2. 需要明确的是，事实上JavaScript并不具有动态作用域。它只有词法作用域，简单明了。但是 this 机制某种程度上很像动态作用域；
词法作用域和动态作用域两者主要区别：词法作用域是在写代码或者说定义时确定的，而动态作用域是在运行时确定的。词法作用域关注函数在何处声明，而动态作用域关注函数从何调用。

**Comment by mumofa** [comment]
#打卡# 键 《图解HTTP》
由于 你不知道的js 上 之前看过了 打算先补上一期的图解补完 再复习一次 js上

1、了解了更多http状态码的信息
2、了解http一些首部报文的各种属性与作用 
3、https的加密过程

**Comment by y925249766** [comment]
#打卡# fish《你不知道的js》

JavaScript中有两个机制可以“欺骗”词法作用域：eval(..)和with。前者可以对一段包含一个或多个声明的“代码”字符串进行演算，并借此来修改已经存在的词法作用域（在运行时）。后者本质上是通过将一个对象的引用当作作用域来处理，将对象的属性当作作用域中的标识符来处理，从而创建了一个新的词法作用域（同样是在运行时）。
这两个机制的副作用是引擎无法在编译时对作用域查找进行优化:
JavaScript引擎会在编译阶段进行数项的性能优化。其中有些优化依赖于能够根据代码的词法进行静态分析，并预先确定所有变量和函数的定义位置，才能在执行过程中快速找到标识符。但如果引擎在代码中发现了eval(..)或with，它只能简单地假设关于标识符位置的判断都是无效的，因为无法在词法分析阶段明确知道eval(..)会接收到什么代码，这些代码会如何对作用域进行修改，也无法知道传递给with用来创建新词法作用域的对象的内容到底是什么。

**Comment by MarcusYZ** [comment]
#打卡# 阳 《你不知道的js上》
附上 [笔记]( https://juejin.im/post/5ca69a8ee51d4521bb0a8096)
读书比起碎片化得看文章能够构建知识体系。
第一周先确定读书方法和读书的目的。
1. 目的：构建起js的地基，丰富完善自己的知识体系，另外让自己可以更加自如得应对js的面试题。
2. 读书方法:
- 第一步先看目录，把目录当做问题，一个一个问自己会与不会，提出一些问题确立重点。
- 第二步速读（不求甚解读），沿着问题和重点翻阅全书,遇到不会的暂时跳过，圈划重点及知识点。就着重点画出思维导图。
- 第三步实践，如果本书或者网上有好的实例边实践边翻书做。
- 第四步慢读，如果没有太好的例子或者书中有很合适的小demo就跳过第三步直接慢读，这遍修正自己的思维导图边读边写用自己的话做一些整理。
- 第五步输出，写作或者讲给别人听，可以读完了再做整体的输出检验自己是否真的听懂，如果内容过多可以分成一块块输出。

**Comment by OliverHzz** [comment]
#打卡# Hz《你不知道的js上》
阅读完第一部分

1. JavaScript 并不具有动态作用域。它只有词法作用域。所以不论函数在何处调用，都会从函数声明的词法作用域中逐级向上查找变量。

2. 变量和函数在内的所有声明都会在任何代码被执行前首先被处理。函数声明和变量声明都会被提升。函数会首先被提升，然后才是变量。

**Comment by y925249766** [comment]
#打卡# fish《你不知道的js》
当函数可以记住并访问所在的词法作用域时，就产生了闭包，即使函数是在当前词法作用域之外执行

**Comment by sichenguo** [comment]
#打卡# Hz《你不知道的js上》

**Comment by CheDabang** [comment]
#打卡 #阿车 《你不知道的js 上》
阅读第一部分
全文分为两个部分、一个部分主要讲的作用域、闭包，第二部分则重点在this和对象原型上面。

第一部部分：
1. 第一章还是LHS、RHS抽象部分的，有点头疼，测试题部分又答错了，感觉不能通俗的表达解释。
2. 第二章词法作用域还好，讲的特性就是查找方式由内到外，这个倒是能够很好理解。还有就是对于骚操作搞什么欺骗词法作用域。当然可以了解一下，就怕有些BT面试题考到这些点。
3.第三章、第四章一直打交道，但是看得很快。两下刷过去，唯一注意的地方，就是知道一项骚操作，try catch居然还能产生块级块级作用的域的效果。有点意思，了解一下，防止BT面试题碰到。
4.闭包还好，老生长谈。面试基本都考的东西，这里讲解闭包的时候，顺便还讲解了一下，模块。让我想起一个设计模式--“工厂模式”。搞的我都想抽空看几大设计模式。

**Comment by y925249766** [comment]
#打卡# fish《你不知道的js》
如果要判断一个运行中函数的this绑定，就需要找到这个函数的直接调用位置。找到之后就可以顺序应用下面这四条规则来判断this的绑定对象。
1.  由new调用？绑定到新创建的对象。2.  由call或者apply（或者bind）调用？绑定到指定的对象。3.  由上下文对象调用？绑定到那个上下文对象。4.  默认：在严格模式下绑定到undefined，否则绑定到全局对象。
一定要注意，有些调用可能在无意中使用默认绑定规则。如果想“更安全”地忽略this绑定，你可以使用一个DMZ对象，比如ø = Object.create(null)，以保护全局对象。
ES6中的箭头函数并不会使用四条标准的绑定规则，而是根据当前的词法作用域来决定this
，具体来说，箭头函数会继承外层函数调用的this绑定（无论this绑定到什么）。这其实和ES6之前代码中的self = this机制一样。

**Comment by heightzhang** [comment]
#打卡 《你不知道的JS》 第一章  笔记&&问题

笔记：
1. V8引擎抛出错误的分类：
抛出 ReferenceError，表示作用域判别不成功。 而TypeError则代表作用域判别成功了，但是对结果的操作是非法或不合理的。

2. LHS查询和RHS查询的区别
LHS查询：赋值操作，如 a = 2
RHS查询：引用变量，如 return a+b ，就包含两次RHS查询，获取a的值，获取b的值

3. 作用域的查找规则
LHS和RHS引用都会在当前楼层进行查找，如果没有找到，就会做电梯前往上一层楼，如果还是没有找到就继续向上，以此类推。一旦抵达顶层（全局作用域），可能找到了你所需的变量，也可能没找到，但无论如何查找过程都将停止。

4.为什么区分LHS和RHS是一件重要的事情？
不成功的RHS引用会导致跑出ReferenceError异常。不成功的LHS引用会导致自动隐士地创建一个全局变量（非严格模式下），该变量使用LHS引用的目的作为标识符，或者跑出ReferenceError异常（严格模式下）

问题：
不成功的LHS引用会导致自动隐士地创建一个全局变量（非严格模式下），如何用代码表示？

**Comment by SHERlocked93** [comment]
#打卡# SHER93 《HTTP/2基础教程》
`h2` 和 `h1` 性能上的差异最让人关心

1. 对于包含很多小型资源的页面，h2 加载页面的时间比 h1 更短。这是因为 h1 下(有 6 个 TCP 连接)服务器只能并行发送 6 个资源(由于队头阻塞)，而 h2 下多个流(stream)可以共用连接。进一步说，随着网络条件变差，h1 和 h2 下页面加载时间(PLT)都会增加；但是 h2 由于单连接，如果唯一的连接发生了丢包，所有工作都会受影响。
2. 对于包含少量大型资源的页面，在所有网络条件下，h1 性能上都比 h2 表现要好。这个多少令人感到意外的结果是初始拥塞窗口导致的。如果开启 6 个连接，h1 的初始拥塞窗口大小实际上是 h2 的 6 倍。因此在会话开始阶段，h2 的连接窗口尚未增长到最佳值，但 h1 早就能更快地传输更多数据了。这个问题目前仍在解决，因为它导致初始拥塞窗口对 h2 而言太小，然而对 h1 而言又太大。 此外，h2 比 h1 更容易受丢包的影响。
3. 对于包含一些极大型资源的 Web 页面，两者没有任何差异。h2 的初始拥塞窗口劣势被整体下载时长掩盖了，多路复用此时也不再具有优势。

**Comment by mumofa** [comment]
#打卡# 键 《图解HTTP》  （其实上周就看完了）
看完发现这本书拿来入门确实不错的  但涉及的内容还是偏少。
如果是要更加深入了解的话，感觉缺少了一些比较关键的知识点，所以我列出来，大家也可以跟着搜索，也算是大厂面试的考点。

1、http1.1 keep-alive复用连接是怎么复用。
2、https的加密过程 也没有很详细的讲解，所以推荐去深入了解，例如CA是如何防止中间人替换证书的
3、tcp的部分好像也讲得比较少。但tcp里几个核心内容觉得有必要了解一下。
tcp的拥塞处理
3.1慢启动 （每个tcp刚建立的时候都不会立刻达到最大功率传输，而是从1窗口，每经过一轮 X 2 达到窗口阀值后启动拥塞避免算法）
3.2 拥塞避免（之前慢启动是每轮窗口X2，启动拥塞避免后，是每轮窗口+1 慢慢调整到最佳数值）
3.3 快速启动和快速恢复（这2个其实差不多，不过讲起来比较复杂，大家可以看下后面的链接了解）

详细可以看 https://yuchengkai.cn/docs/cs/#%E6%8B%A5%E5%A1%9E%E5%A4%84%E7%90%86

**Comment by wenming-web** [comment]
1. LHS 为赋值操作，RHS 为取值操作，引用、调用等都可理解为取值操作，因此都是RHS。值的操作除了赋值即为取值。因此除赋值操作为LHS外，可认为其他操作皆为RHS。
2. JavaScript只有词法作用域。但是 this 的绑定在部分情况下会动态的变化，让人误解成动态作用域。
3. this 在默认绑定中在对象属性引用链中只有最顶层或者说最后一层会影响调用位置，最顶层或者说最后一层应该就是最近的一层。
以上都为个人理解，如有错误，欢迎指正。

**Comment by SHERlocked93** [comment]
> 1. LHS 为赋值操作，RHS 为取值操作，引用、调用等都可理解为取值操作，因此都是RHS。值的操作除了赋值即为取值。因此除赋值操作为LHS外，可认为其他操作皆为RHS。
> 2. JavaScript只有词法作用域。但是 this 的绑定在部分情况下会动态的变化，让人误解成动态作用域。
> 3. this 在默认绑定中在对象属性引用链中只有最顶层或者说最后一层会影响调用位置，最顶层或者说最后一层应该就是最近的一层。
>    以上都为个人理解，如有错误，欢迎指正。

为了方便记录打卡进度，打卡标题的格式是 `#打卡# 键 《图解HTTP》 ` 这样~

**Comment by teachat8** [comment]
#打卡# sweet《你不知道的js上册》
1. 代码先编译后执行，当编译器在编译过程的第二步中生成了代码，引擎执行它时，会通过查找变量 a 来判断它是否已经声明过。查找的过程由作用域进行协助，但是引擎执行怎样的查找，会影响最终的查找结果。对 JavaScript 引擎的性能要求很高。
2. 词法作用域只由函数被声明时所处的位置决定。
3. 副作用是引擎无法在编译时对作用域查找进行优化。因为引擎只能谨慎地认为这样的优化是无效的，使用任何一个机制都将导致代码运行变慢。

**Comment by Java-http** [comment]
#打卡# 鑫 《你不知道的js中册》
分享：
要为某个缺失的功能写 polyfill,如何避免重复声明变量？
1. 使用 typeof 判断
```
if (typeof atob === "undefined") { // typeof 后面跟有未声明的变量会防止报错
 atob = function() { /*..*/ }; // 去掉 var 则可以防止声明被提升
}
```
2. 检查所有全局变量是否是全局对象的属性，浏览器中的全局对象是 window。
3. 依赖注入的方式

**Comment by SHERlocked93** [comment]
> #打卡# 鑫 《你不知道的js中册》
> 分享：
> 要为某个缺失的功能写 polyfill,如何避免重复声明变量？
> 
> 1. 使用 typeof 判断
> 
> ```
> if (typeof atob === "undefined") { // typeof 后面跟有未声明的变量会防止报错
>  atob = function() { /*..*/ }; // 去掉 var 则可以防止声明被提升
> }
> ```
> 1. 检查所有全局变量是否是全局对象的属性，浏览器中的全局对象是 window。
> 2. 依赖注入的方式

这个依赖注入的方式何解

**Comment by OliverHzz** [comment]
#打卡# Hz《你不知道的js上》

1. for..of 语法来遍历会寻找内置或者自定义的 @@iterator 对象并调用它的 next() 方法来遍历数据值。

2.  箭头函数会绑定当前作用域上下文中的this，与它的调用方式无关。

3. in不仅查找查找当前对象是否存在此属性，还会根据原型链查找属性是否存在，hasOwnProperty只查找当前对象是否存在此属性。

**Comment by MarcusYZ** [comment]
#打卡# 阳 《你不知道的js上册》
1. 执行上下文是执行JavaScript代码环境的抽象概念，每当代码运行时都在执行上下文中运行。执行上下文分全局执行上下文，函数执行上下文，eval执行上下文。

2. 执行栈在别的语言中叫调用栈，JavaScript引擎遇到你的脚本会创建一个全局执行上下文推入到执行栈中，遇到一个函数的调用就会创建一个执行上下文并推入到执行栈中，当执行完毕后就会把该执行上下文推出执行栈，进入下一个执行上下文。

3. 每一个执行上下文的创建包括，把当前执行上下文赋给this，严格模式下undefined；还有词法环境；变量环境。词法环境内部包含环境记录器和外部环境的引用，变量环境也是一种词法作用域。

**Comment by SHERlocked93** [comment]
#打卡# SHER93 《HTTP/2基础教程》

h1 下的一些性能调优办法在 h2 下会起到反作用：

| 名称               | 描述                                                         | 备注                                                         |
| ------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| 资源合并           | 把多个文件（JavaScript、CSS） 合成一个文件，以减少 HTTP 请求 | 在 HTTP/2 下这并非必要，因为请求的传输字节数和时间成本更低，虽然这种成本仍然存在 |
| 极简化             | 去除 HTML、JavaScript、CSS 这类文件中无用的代码              | 很棒的做法，在 HTTP/2 下也要保留                             |
| 域名拆分           | 把资源分布到不同的域名上面去，让浏览器利用更多的 socket 连接 | HTTP/2 的设计意图是充分利用单个 socket 连接，而拆分域名会违背这种意图。建议取消域名拆分，但请注意本表格之后的附注框会介绍这个问题相关的各种复杂情况 |
| 禁用 cookie 的域名 | 为图片之类的资源建立单独的域名，这些域名不用 cookie，以尽可能减少请求尺寸 | 应该避免为这些资源单独设立域名（参见域名拆分），但更重要的是，由于 HTTP/2 提供了首部压缩，cookie 的开销会显著降低 |
| 生成精灵图         | 把多张图片拼合为一个文件，使用 CSS 控制在 Web 页面上展示的部分 | 与极简化类似，只不过用 CSS 实现这种效果的代价高昂；不推荐在 HTTP/2 中使用 |

**Comment by mumofa** [comment]
#打卡# 键 《Web性能权威指南》 （看完图解http后继续补http内容）
目前只看了第一部分 包括延迟与带宽的联系，与TCP、UDP的构成。

1、TCP部分比较详细地讲解了拥塞预防和控制的情况。这部分提到最多的部分就是 `窗口`，如果你发送端或接收端的窗口有限，即使你带宽再高，传输效率也不会快。
2、UDP 它与TCP有很大区别，因为UDP并不需要建立连接，不会管接收端的情况，不会有重发机制。所以它的实时性也很高，目前直播端的一些协议（webRTC）就使用了UDP。

**Comment by junjunj** [comment]
#打卡# 俊俊酱《你不知道的js上》

**Comment by sichenguo** [comment]
#打卡# sweet《你不知道的js上册》
- 包装函数的声明以 (function... 而不仅是以 function... 开始。尽管看上去这并不是一个很显眼的细节，但实际上却是非常重要的区别。函数会被当作函数表达式而不是一个标准的函数声明来处理。根据function是否为声明的第一个词
- 匿名函数表达式，因为 function().. 没有名称标识符。函数表达式可以是匿名的， 而函数声明则不可以省略函数名——在 JavaScript 的语法中这是非法的。

**Comment by teachat8** [comment]
#打卡# sweet 《你不知道的js上册》
判断一个运行中函数的 this 绑定:
1. 由new调用?绑定到新创建的对象。
2. 由call或者apply(或者bind)调用?绑定到指定的对象。
3. 由上下文对象调用?绑定到那个上下文对象。
4. 默认:在严格模式下绑定到undefined，否则绑定到全局对象。

**Comment by y925249766** [comment]
myObject.a的属性访问返回值可能是undefined，但是这个值有可能是属性中存储的undefined，也可能是因为属性不存在所以返回undefined。那么如何区分这两种情况呢？
我们可以在不访问属性值的情况下判断对象中是否存在这个属性：
var myObject = {a:2 };  ("a" in myObject); // true ("b" in myObject); // false   myObject.hasOwnProperty( "a" ); // true myObject.hasOwnProperty( "b" ); // false
in操作符会检查属性是否在对象及其[[Prototype]]原型链中。相比之下，hasOwnProperty(..)只会检查属性是否在 myObject对象中，不会检查[[Prototype]]链。

**Comment by CheDabang** [comment]
#打卡#  阿车 《你不知道的js上册》
第二部分:  前面2章，讲的是this。面试率极高的一个知识点，也是工作coding会遇到到问题。
第一章的小结部分，就很精髓的总结了：

> this实际上是在函数被调用时发生的绑定，它指向什么完全取决于函数在哪里被调用。

ES5的确this有好多坑要注意，不过还好ES6的箭头函数的this指向就简单粗暴好多。

**Comment by Java-http** [comment]
> > #打卡# 鑫 《你不知道的js中册》
> > 分享：
> > 要为某个缺失的功能写 polyfill,如何避免重复声明变量？
> > 
> > 1. 使用 typeof 判断
> > 
> > ```
> > if (typeof atob === "undefined") { // typeof 后面跟有未声明的变量会防止报错
> >  atob = function() { /*..*/ }; // 去掉 var 则可以防止声明被提升
> > }
> > ```
> > 
> > 1. 检查所有全局变量是否是全局对象的属性，浏览器中的全局对象是 window。
> > 2. 依赖注入的方式
> 
> 这个依赖注入的方式何解

还有一些人喜欢使用“依赖注入”（dependency injection）设计模式，就是将依赖通过参数
显式地传递到函数中，如：
```
function doSomethingCool(FeatureXYZ) {
 var helper = FeatureXYZ ||
 function() { /*.. default feature ..*/ };
 var val = helper();
 // ..
}
```

**Comment by Java-http** [comment]
#打卡# 鑫 《你不知道的js中册》
分享小技巧：
1: ~ 和 ~~ 的作用 (了解一下)
~x 大致等同于 -(x+1);
~~x 能将值截除为一个 32 位整数，x | 0 也可以，而且看起来还更简洁;
2. parseInt 需要注意它的第二个参数，见下面一道面试题
`["1", "2", "3"].map(parseInt)` 返回 `[1,NaN,NaN]`

**Comment by CheDabang** [comment]
#打卡# 阿车 《你不知道的js上册》
1、以前一直只是知道typeof null会返回object，但是一直不知道具体的原因。看书才知道不同的对象在底层都表示为二进制，在JavaScript中二进制前三位都为0的话会被判断为object类型，null的二进制表示是全0，自然前三位也是0，所以执行typeof时会返回“object”。
2、对象[键]语法，这个键名比属于语法更自由，不需要考虑标识是否规范。当然一把对象存储的也是规范的。
3、关于对象属性，如可读性、可枚举一类，开扩思路，以前从来没有想到一个对象属性还能这么写。

> 最近有点忙，这本书看囫囵吞枣。抽空还是得重新再刷一遍看看。

**Comment by SHERlocked93** [comment]
#打卡# SHER93 《单核工作法图解》
所谓**单核工作法**，就是在设定好的时间内，一次只做一件事，与此同时，又根据变化着的全局重新设定工作重心。
面对很多任务，我们可以更有效率：

1. 不要开启那么多新任务，而要先完成已经决定要做的任务；
2. 优先处理更重要的任务，而不是最紧急的任务；
3. 一次只专注与一项工作，我们的大脑结构更适合一次处理一件事；

**Comment by OliverHzz** [comment]
#打卡# Hz《你不知道的js上》

1.  Object.create(null) 可创建纯净的对象，不带有任何原型。

2. JavaScript 中这个机制的本质就是对象之间的关联关系。根据原型链进行关联。

**Comment by teachat8** [comment]
#打卡# sweet《你不知道的js上》
1. 普通对象都有Object.prototype，指向原型链的顶端(比如说全局作用域)，如果在原型链中找不到指定的属性就会停止。toString()、valueOf() 和其他一些通用的功能 都存在于 Object.prototype 对象上。
2. 如果在第一个对象上没有找到需要的属性或者方法引用，引擎就会继续在 [[Prototype]] 关联的对象上进行查找。同理，如果在后者中也没有找到需要的引用就会继续查找它的 [[Prototype]]，以此类推。这一系列对象的链接被称为“原型链”。
3. 关联两个对象最常用的方法是使用 new 关键词进行函数调用。

**Comment by y925249766** [comment]
#打卡# fish《你不知道的js上》

类是一种设计模式。许多语言提供了对于面向类软件设计的原生语法。JavaScript也有类似的语法，但是和其他语言中的类完全不同。
类意味着复制。
传统的类被实例化时，它的行为会被复制到实例中。类被继承时，行为也会被复制到子类中。
多态（在继承链的不同层次名称相同但是功能不同的函数）看起来似乎是从子类引用父类，但是本质上引用的其实是复制的结果。
JavaScript并不会（像类那样）自动创建对象的副本。

**Comment by SHERlocked93** [comment]
> #打卡# Hz《你不知道的js上》
> 
> 1. for..of 语法来遍历会寻找内置或者自定义的 @@iterator 对象并调用它的 next() 方法来遍历数据值。
> 2. 箭头函数会绑定当前作用域上下文中的this，与它的调用方式无关。
> 3. in不仅查找查找当前对象是否存在此属性，还会根据原型链查找属性是否存在，hasOwnProperty只查找当前对象是否存在此属性。

这个 `iterator` 就是迭代器模式吧，就是因为使用了迭代器模式，所以使用 `for···of` 避免了使用 `forEach` 的时候一次发送所有 query 的情况

**Comment by mumofa** [comment]
#打卡# 键《Web性能权威指南》

看到第三部分。 第二部分建议跳过 可以粗略看一下，讲得是wifi和移动网络方面，感兴趣可以仔细看看。

1、http简史 粗略讲解了一下http的进化历程
2、web性能要点  这里书中提出的观点是，带宽不是影响网页打开速度的瓶颈，网络延迟才是。因为除开下载、看视频外，正常带宽利用率很低，影响性能的最重要指标是每次通讯往返的通讯时间，如果能将100ms降到50ms甚至20ms 性能会有非常高的提高。

![yanchi.png](https://i.loli.net/2019/04/30/5cc7e58eddfab.png)

**Comment by SHERlocked93** [comment]
> #打卡# 键《Web性能权威指南》
> 
> 看到第三部分。 第二部分建议跳过 可以粗略看一下，讲得是wifi和移动网络方面，感兴趣可以仔细看看。
> 
> 1、http简史 粗略讲解了一下http的进化历程
> 2、web性能要点 这里书中提出的观点是，带宽不是影响网页打开速度的瓶颈，网络延迟才是。因为除开下载、看视频外，正常带宽利用率很低，影响性能的最重要指标是每次通讯往返的通讯时间，如果能将100ms降到50ms甚至20ms 性能会有非常高的提高。
> 
> ![yanchi.png](https://camo.githubusercontent.com/04134bddefb04427a531c70a9b54176881e8e02b/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30342f33302f356363376535386564646661622e706e67)

那如何有效降低网络延迟呢

**Comment by mumofa** [comment]
> > #打卡# 键《Web性能权威指南》
> > 看到第三部分。 第二部分建议跳过 可以粗略看一下，讲得是wifi和移动网络方面，感兴趣可以仔细看看。
> > 1、http简史 粗略讲解了一下http的进化历程
> > 2、web性能要点 这里书中提出的观点是，带宽不是影响网页打开速度的瓶颈，网络延迟才是。因为除开下载、看视频外，正常带宽利用率很低，影响性能的最重要指标是每次通讯往返的通讯时间，如果能将100ms降到50ms甚至20ms 性能会有非常高的提高。
> > ![yanchi.png](https://camo.githubusercontent.com/04134bddefb04427a531c70a9b54176881e8e02b/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30342f33302f356363376535386564646661622e706e67)
> 
> 学到了，「带宽不是影响网页打开速度的瓶颈，网络延迟才是」，那如何有效降低网络延迟呢

其实这部分前端能做到的部分很少，不过还是有以下几点可以做到。
![image](https://user-images.githubusercontent.com/13733330/56943457-27c19880-6b52-11e9-977f-cf981045cb23.png)

我们怎么利用浏览器的这些机制呢？首先，要密切关注每个页面的结构和交付：
![image](https://user-images.githubusercontent.com/13733330/56943518-753e0580-6b52-11e9-8a37-b1a1f06e0b1e.png)

除了优化页面结构，还可以在文档中嵌入提示，以触发浏览器为我们采用其他优化机制：
![image](https://user-images.githubusercontent.com/13733330/56943533-8129c780-6b52-11e9-8b81-4587566a98c3.png)

这些标识符可能不能所有浏览器都支持，但就算不支持也只是没有效果罢了，有益无害，所以可以看看自己项目中有没有添加这些预解析标识~

**Comment by SHERlocked93** [comment]
> ...
> 这些标识符可能不能所有浏览器都支持，但就算不支持也只是没有效果罢了，有益无害，所以可以看看自己项目中有没有添加这些预解析标识~

大部分都是一些资源预取的操作，这些首段在首屏优化都用不到，看来前端能做的还真不多

**Comment by sichenguo** [comment]
# 打卡# gkr 《深入浅出react和redux》

最近看了前三章

- react 的理念是 ui= render(data)， render()是一个没有任何 **副作用** 且输出完全依赖于输出的纯函数。利用函数式编程来解决用户界面渲染的问题。
- 易于维护的组件的设计要素
  - 高内聚 将逻辑紧密相关的内容放在一个组件中。而react的展示内容的jsx，定义行为的js代码都放在一个文件中，天生具有高内聚的特点。
  - 低耦合 不同组件之间的依赖关系需要尽量弱化，每个组件需要尽量保持独立。进而保持整个系统的低耦合性
- MVC框架的缺陷
  - MVC提出的数据流很理想，用户的请求首先到达Controller,由Controller调用model获得数据，然后把数据交给view,但是在实际框架实现中，总是会允许view 可以直接通信。这样的话对于体量比较大项目而言，后期的功能的扩展以及维护就会变得困难，因为模块之间的依赖关系会使得系统变得脆弱且不可预测。所以需要更加严格的数据流控制。

**Comment by MarcusYZ** [comment]
#打卡# 阳 《你不知道的js 上》
1.  js中的任何函数都可以被new操作符当做构造函数，不过他们的目的是用来构造，实际上却是调用。
2.  所有的对象都有内置的Object.prototype，指向原型链的顶端，在使用new调用函数的时候会把新对象的.prototype属性关联到”其他对象“。在此原型链中不到指定的属性就会定制。
3. js编程有一个更好的编程模式，委托。它不像类风格的代码那样复制，而是让对象之间产生关联，创建好的对象中好像有很多坑，如果遇到坑就会通过原型链到它的上层去找。
这几个风格的设计模式还是有点混乱，还需要辨析与学习。
