### ISSUE TITLE
#打卡# 明《你不知道的js上册》

### ISSUE THREAD

**Issue by wenming-web** [Read-Book2019/Schedule#7]
#打卡# 明《你不知道的js上册》
1. LHS 为赋值操作，RHS 为取值操作，引用、调用等都可理解为取值操作，因此都是RHS。值的操作除了赋值即为取值。因此除赋值操作为LHS外，可认为其他操作皆为RHS。
2.JavaScript只有词法作用域。但是 this 的绑定在部分情况下会动态的变化，让人误解成动态作用域。
3.this 在默认绑定中在对象属性引用链中只有最顶层或者说最后一层会影响调用位置，最顶层或者说最后一层应该就是最近的一层。
以上都为个人理解，如有错误，欢迎指正。

**Comment by SHERlocked93** [comment]
打卡是直接在之前的 #6  里面打哦 ~
